services:
  - type: web
    name: bernardofernandezdev
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: "https://bernardofernandez.github.io/bernardofernandezdev/pages/about/about.html"
      - key: REDIRECT_URI
        value: "https://bernardofernandezdev.onrender.com/callback"
      - key: ALLOWED_ORIGINS
        value: "https://bernardofernandez.github.io"
